jwt:
  secretKey: sdfgfgdsfg7sd890fgsdfgsidfjgskdjfhglwut9w834ut90jkfjsdfgw9483utoegdfklgndfgowejt59u6
spring:
  application:
    name: api-gateway
  #api gateway config
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            #            - RedirectTo=302, http://codingshuttle.com
            - name: LoggingOrdersFilter
            - name: Authentication
              args:
                Enabled: true
        #            - name: Authorization
        #              args:
        #                allowedRoles: ADMIN, SUPER_ADMIN
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, Anuj
            - name: Authentication
              args:
                Enabled: true


server:
  port: 8080
